[build]
  command = "npm run build"
  publish = "." 
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "file:./dev.db"  