[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.cache]
  base = "$HOME/.cache"
  directories = [
    ".next/cache",
    "node_modules/.cache",
    "node_modules/.prisma"
  ]

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

