import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
       <Providers>
          <Header/>
          <div className="max-w-[1024px] px-6 mt-5 mx-auto">
            {children}
          </div>
       </Providers>
      </body>
    </html>
  );
}
